<?php
/**
 * Wave payroll import + shareholder account (migration 1255): parsing a report with Wave's
 * layout (synthetic — fake names and amounts), monthly totals and the hours split, the
 * journal entry balancing, bank matching (Wave pays CRA: WAVE PYRL debits = remittance,
 * e-Transfers = net pay, the shareholder's transfers split into pay + 1300), locked months,
 * approve / undo, repayments, the clearing entry and the running balance.
 */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/BankLineMoveServiceTest.php';   // its SQLite schema

final class WavePayrollImportServiceTest extends TestCase
{
    // Jane Doe (crew) and Pat Owner (the shareholder) — invented.
    private const JANE = ['fed' => [150.00, 0], 'prov' => [60.00, 0], 'ei' => [32.60, 45.64], 'cpp' => [109.00, 109.00], 'cpp2' => [0, 0]];
    private const PAT = ['fed' => [400.00, 0], 'prov' => [150.00, 0], 'ei' => [0, 0], 'cpp' => [163.50, 163.50], 'cpp2' => [0, 0]];

    /** A report with Wave's layout (as smalot/pdfparser reads it). */
    public static function report(string $from, string $to, array $emps): string
    {
        $labels = ['fed' => 'Federal Tax', 'prov' => 'Provincial Tax', 'ei' => 'Employment Insurance', 'cpp' => 'Canada Pension Plan', 'cpp2' => 'Second additional CPP contribution'];
        $m = fn($v) => '$' . number_format($v, 2);
        $sum = [];
        $wagesAll = 0.0;
        foreach ($emps as $e) {
            $wagesAll += $e['wages'];
            foreach ($e['tax'] as $k => $v) { $sum[$k][0] = ($sum[$k][0] ?? 0) + $v[0]; $sum[$k][1] = ($sum[$k][1] ?? 0) + $v[1]; }
        }
        $t = "MOWOLOGY Wage & Tax Report\nBusiness Address\n1 Test Street\nVancouver, BC V0V 0V0\nCanada\nFor all paydays\nduring\n{$from} to\n{$to}\nCreated on10/07/2026\nEmployer Summary\n"
           . "Wages Taxed Wages Employee\nAmount\nEmployer\nAmount\nTax Liability\n";
        foreach ($labels as $k => $label) {
            $t .= $label . ($k === 'cpp2' ? ' ' : "\t") . $m($wagesAll) . ' ' . $m($wagesAll) . ' ' . $m($sum[$k][0]) . ' ' . $m($sum[$k][1]) . ' ' . $m($sum[$k][0] + $sum[$k][1]) . "\n";
        }
        foreach ($emps as $e) {
            $t .= $e['last'] . ', ' . $e['first'] . "\nName\tWages Taxed Wages Employee\nWithheld\nEmployer\nExpense\nTax Liability\n";
            foreach ($labels as $k => $label) {
                $v = $e['tax'][$k];
                $t .= $label . "\t" . $m($e['wages']) . ' ' . $m($e['wages']) . ' ' . $m($v[0]) . ' ' . $m($v[1]) . "\t" . $m($v[0] + $v[1]) . "\n";
            }
            $t .= "Payday\tPayroll Period Regular Overtime Double Time Vacation Sick\n";
            foreach ($e['paydays'] as $p) $t .= "{$p[0]} {$p[1]} to {$p[2]} {$p[3]}\t0.0\t0.0 " . round($p[3] * 0.04, 2) . " 0.0\n";
            $t .= "Total Hours\t1.0\t0.0\t0.0 0.0 0.0\nWage and Tax Report generated by Wave Financial\n\n";
        }
        return $t;
    }

    private static function janJane(): array
    {
        return ['first' => 'Jane', 'last' => 'Doe', 'wages' => 2000.00, 'tax' => self::JANE,
                'paydays' => [['01/15/2026', '12/29/2025', '01/11/2026', 40.0], ['01/29/2026', '01/12/2026', '01/25/2026', 40.0]]];
    }

    private static function janPat(): array
    {
        return ['first' => 'Pat', 'last' => 'Owner', 'wages' => 3000.00, 'tax' => self::PAT,
                'paydays' => [['01/15/2026', '12/29/2025', '01/11/2026', 80.0], ['01/29/2026', '01/12/2026', '01/25/2026', 80.0]]];
    }

    private static function january(): string
    {
        return self::report('01/01/2026', '01/31/2026', [self::janJane(), self::janPat()]);
    }

    // ── Parse + months (pure) ───────────────────────────────────────────────

    public function testParsesTheReportLayout(): void
    {
        $p = WavePayrollImportService::parse(self::january());
        $this->assertSame('2026-01-01', $p['from']);
        $this->assertSame('2026-01-31', $p['to']);
        $this->assertSame([], $p['warnings']);
        $this->assertCount(2, $p['employees']);
        $this->assertSame('Jane Doe', $p['employees'][0]['name']);
        $this->assertCount(2, $p['employees'][0]['paydays']);
        $this->assertSame(['payday' => '2026-01-15', 'period_start' => '2025-12-29', 'period_end' => '2026-01-11', 'regular' => 40.0, 'overtime' => 0.0,
                           'double_time' => 0.0, 'vacation' => 1.6, 'sick' => 0.0], $p['employees'][0]['paydays'][0]);
        $j = $p['employees'][0]['totals'];
        $this->assertSame(2000.0, $j['wages']);
        $this->assertSame(351.6, $j['withholdings']);
        $this->assertSame(1648.4, $j['net']);
        $this->assertSame(154.64, $j['employer']);
        $this->assertSame(506.24, $j['remittance']);
        $this->assertSame(['wages' => 5000.0, 'taxed' => 5000.0, 'ee' => 272.5, 'er' => 272.5, 'liability' => 545.0], $p['summary']['cpp']);
    }

    public function testEmployeesThatDontAddUpToTheSummaryAreFlagged(): void
    {
        $text = str_replace("Federal Tax\t\$5,000.00 \$5,000.00 \$550.00", "Federal Tax\t\$5,000.00 \$5,000.00 \$560.00", self::january());
        $text = str_replace('$560.00 $0.00 $550.00', '$560.00 $0.00 $560.00', $text);
        $p = WavePayrollImportService::parse($text);
        $this->assertNotEmpty($p['warnings']);
        $this->assertStringContainsString('Federal Tax', $p['warnings'][0]);
    }

    public function testOneMonthReportIsExact(): void
    {
        $months = WavePayrollImportService::months(WavePayrollImportService::parse(self::january()));
        $this->assertSame(['2026-01'], array_keys($months));
        $m = $months['2026-01'];
        $this->assertFalse($m['estimate']);
        $this->assertSame('2026-01-29', $m['last_payday']);
        $this->assertSame(5000.0, $m['totals']['wages']);
        $this->assertSame(3934.9, $m['totals']['net']);
        $this->assertSame(1383.24, $m['totals']['remittance']);
    }

    public function testMultiMonthReportIsSplitByHoursAndAddsBackUp(): void
    {
        $jane = self::janJane();
        $jane['paydays'][1] = ['02/12/2026', '01/26/2026', '02/08/2026', 120.0];   // 40 h in Jan, 120 h in Feb
        $pat = self::janPat();
        $p = WavePayrollImportService::parse(self::report('01/01/2026', '02/28/2026', [$jane, $pat]));
        $months = WavePayrollImportService::months($p);
        $this->assertSame(['2026-01', '2026-02'], array_keys($months));
        $this->assertTrue($months['2026-01']['estimate']);
        $jan = $months['2026-01']['employees'][0]['totals'];
        $feb = $months['2026-02']['employees'][0]['totals'];
        $this->assertSame(500.0, $jan['wages'], '41.6 of 166.4 paid hours');
        $this->assertSame(1500.0, $feb['wages']);
        $this->assertSame(2000.0, round($jan['wages'] + $feb['wages'], 2));
        $this->assertSame(1648.4, round($jan['net'] + $feb['net'], 2));
        $this->assertSame(506.24, round($jan['remittance'] + $feb['remittance'], 2));
        $this->assertCount(1, $months['2026-02']['employees'], 'Pat had no February payday');
    }

    public function testJournalEntryBalancesWithAndWithoutTheShareholderSweep(): void
    {
        $t = WavePayrollImportService::months(WavePayrollImportService::parse(self::january()))['2026-01']['totals'];
        foreach ([0.0, 1213.5, -300.0] as $sweep) {
            $e = WavePayrollImportService::buildEntry($t, $sweep, '2026-01-29', 'Wave payroll');
            $dr = round(array_sum(array_column($e['lines'], 'debit')), 2);
            $cr = round(array_sum(array_column($e['lines'], 'credit')), 2);
            $this->assertSame($dr, $cr, "sweep {$sweep}");
            (new LedgerService(new PDO('sqlite::memory:')))->validateEntry(['lines' => array_map(fn($l) => $l + ['account_id' => 1], $e['lines'])]);
        }
        $e = WavePayrollImportService::buildEntry($t, 0.0, '2026-01-29', 'x');
        $by = [];
        foreach ($e['lines'] as $l) $by[$l['account']] = [$l['debit'], $l['credit']];
        $this->assertEquals([5000.0, 0], $by['5100']);
        $this->assertEquals([318.14, 0], $by['5110']);
        $this->assertEquals([0, 1383.24], $by['2310']);
        $this->assertEquals([0, 3934.9], $by['2520']);
    }

    // ── Matching (pure) ─────────────────────────────────────────────────────

    private static function bank(): array
    {
        $l = fn($id, $d, $a, $desc, $dir = 'out', $code = '5100') => ['id' => $id, 'date' => $d, 'amount' => $a, 'description' => $desc, 'direction' => $dir, 'account_code' => $code];
        return [
            $l(1, '2026-01-13', 691.62, 'WAVE PYRL 0012345'),
            $l(2, '2026-01-27', 691.62, 'WAVE PYRL 0012399'),
            $l(3, '2026-01-15', 824.20, 'ETRANSFER DEBIT (JANE DOE)'),
            $l(4, '2026-01-29', 824.20, 'ETRANSFER DEBIT (JANE DOE)'),
            $l(5, '2026-01-15', 1500.00, 'ETRANSFER DEBIT (PAT OWNER)', 'out', '3300'),
            $l(6, '2026-01-20', 500.00, 'ETRANSFER DEBIT (PAT OWNER)', 'out', '3300'),
            $l(7, '2026-01-29', 1500.00, 'ETRANSFER DEBIT (PAT OWNER)', 'out', '3300'),
            $l(8, '2026-01-31', 61.60, 'WAVE - PAYROLL FEES'),
            $l(9, '2026-01-10', 300.00, 'COSTCO WHOLESALE', 'out', '5200'),
            $l(10, '2026-01-25', 400.00, 'ETRANSFER CREDIT (PAT OWNER)', 'in', '4900'),
        ];
    }

    public function testWavePaysCraAndEveryoneIsMatched(): void
    {
        $m = WavePayrollImportService::months(WavePayrollImportService::parse(self::january()))['2026-01'];
        $claimed = [];
        $r = WavePayrollImportService::matchMonth($m, self::bank(), 'Pat Owner', $claimed);
        $this->assertSame('match', $r['remittance']['status']);
        $this->assertEqualsCanonicalizing([1, 2], $r['remittance']['ids']);
        $this->assertSame('match', $r['employees'][0]['status']);
        $this->assertEqualsCanonicalizing([3, 4], $r['employees'][0]['ids']);
        $this->assertSame([8], $r['fees']);
        // The shareholder: $3,500 to himself, $2,286.50 of it is pay, $1,213.50 a withdrawal.
        $this->assertSame(2286.5, $r['shareholder']['net']);
        $this->assertSame(3500.0, $r['shareholder']['transfers']);
        $this->assertSame(1213.5, $r['shareholder']['sweep']);
        $this->assertSame(['source_deductions' => 0.0, 'net_pay' => 0.0, 'sweep' => 1213.5], $r['clearing']);
        $ids = array_column($r['moves'], 'id');
        $this->assertNotContains(9, $ids, 'unrelated spending is left alone');
        $this->assertNotContains(10, $ids, 'money in is the shareholder account\'s business, not payroll');
        foreach ($r['moves'] as $mv) $this->assertTrue($mv['checked']);
        $to = array_column($r['moves'], 'to', 'id');
        ksort($to);
        $this->assertSame([1 => '2310', 2 => '2310', 3 => '2520', 4 => '2520', 5 => '2520', 6 => '2520', 7 => '2520', 8 => '6800'], $to);
    }

    public function testRemittanceThatDoesNotAddUpIsOfferedUnticked(): void
    {
        $m = WavePayrollImportService::months(WavePayrollImportService::parse(self::january()))['2026-01'];
        $bank = self::bank();
        $bank[1]['amount'] = 650.00;
        $claimed = [];
        $r = WavePayrollImportService::matchMonth($m, $bank, 'Pat Owner', $claimed);
        $this->assertSame('differs', $r['remittance']['status']);
        $this->assertSame(1341.62, $r['remittance']['found']);
        $this->assertSame(41.62, $r['remittance']['diff']);
        foreach ($r['moves'] as $mv) if ($mv['role'] === 'remittance') $this->assertFalse($mv['checked']);
        $this->assertSame(1383.24, $r['clearing']['source_deductions'], 'nothing ticked → the whole remittance still owed');
    }

    public function testShareholderShortOfHisNetLeavesWagesOwedToHim(): void
    {
        $this->assertSame(['net_pay' => 2286.5, 'to_shareholder' => 1213.5], ShareholderAccountService::split(3500, 2286.5));
        $this->assertSame(['net_pay' => 2000.0, 'to_shareholder' => -286.5], ShareholderAccountService::split(2000, 2286.5));
        $m = WavePayrollImportService::months(WavePayrollImportService::parse(self::january()))['2026-01'];
        $bank = array_values(array_filter(self::bank(), fn($l) => !in_array($l['id'], [6, 7], true)));
        $claimed = [];
        $r = WavePayrollImportService::matchMonth($m, $bank, 'Pat Owner', $claimed);
        $this->assertSame(-786.5, $r['shareholder']['sweep'], '$1,500 paid against $2,286.50 owed → reduces what he owes');
        $this->assertSame(0.0, $r['clearing']['net_pay']);
    }

    public function testNamesSharedInAFamilyNeedTheFirstName(): void
    {
        $all = [['name' => 'Pat Owner', 'first' => 'Pat', 'last' => 'Owner'], ['name' => 'Sam Owner', 'first' => 'Sam', 'last' => 'Owner'], ['name' => 'Jane Doe', 'first' => 'Jane', 'last' => 'Doe']];
        $this->assertTrue(WavePayrollImportService::nameMatches('ETRANSFER DEBIT (SAM OWNER)', $all[1], $all));
        $this->assertFalse(WavePayrollImportService::nameMatches('ETRANSFER DEBIT (SAM OWNER)', $all[0], $all));
        $this->assertFalse(WavePayrollImportService::nameMatches('ETRANSFER DEBIT OWNER', $all[0], $all), 'last name shared → not enough');
        $this->assertTrue(WavePayrollImportService::nameMatches('E-TFR JANE D', $all[2], $all), 'unique first name');
        $this->assertNull(WavePayrollImportService::subsetSum([1 => 10.0, 2 => 20.0], 25.0));
        $this->assertEqualsCanonicalizing([1, 2], WavePayrollImportService::subsetSum([1 => 10.0, 2 => 20.0, 3 => 50.0], 30.0));
    }

    public function testACodeNamedForSomethingElseIsRefused(): void
    {
        $ok = ['5100' => 'Labour — Crew Wages', '5110' => 'Employer CPP & EI', '2310' => 'Source deductions payable — CRA',
               '2520' => 'Net pay clearing — Wave', '1300' => 'Due from Shareholder', '6800' => 'Bank Charges & Fees'];
        $this->assertSame([], WavePayrollImportService::accountProblems($ok));
        $p = WavePayrollImportService::accountProblems(['2310' => 'Income Tax Payable'] + $ok);
        $this->assertCount(1, $p, 'income tax payable (2510 on prod) is never used for source deductions');
        $this->assertSame('2310', WavePayrollImportService::ACC_SOURCE_DEDUCTIONS);
    }

    public function testBriefFromTheFifthWhenLastMonthIsMissing(): void
    {
        $this->assertSame([], WavePayrollImportService::briefItems([], true, '2026-10-04'));
        $i = WavePayrollImportService::briefItems(['2026-08'], true, '2026-10-05');
        $this->assertCount(1, $i);
        $this->assertSame('penny:payroll:2026-09', $i[0]['key']);
        $this->assertStringContainsString('September payroll report', $i[0]['text']);
        $this->assertSame([], WavePayrollImportService::briefItems(['2026-09'], true, '2026-10-05'));
        $this->assertSame([], WavePayrollImportService::briefItems([], false, '2026-10-05'), 'no payroll in use');
        $this->assertSame([], ShareholderAccountService::briefItems(5000, '2026-10-07'));
        $this->assertCount(1, ShareholderAccountService::briefItems(5000, '2026-11-02'));
        $this->assertSame([], ShareholderAccountService::briefItems(100, '2026-12-02'));
    }

    public function testRunningBalance(): void
    {
        // Opens with the company owing him $14 (updated FY2025 FS, after the $86,100 dividend).
        $r = ShareholderAccountService::running(-14.0, [
            ['month' => '2026-01', 'kind' => 'withdrawal', 'amount' => 500.0],
            ['month' => '2026-01', 'kind' => 'payroll', 'amount' => 1213.5],
            ['month' => '2026-02', 'kind' => 'repayment', 'amount' => -400.0],
            ['month' => '2026-03', 'kind' => 'clearing', 'amount' => -1299.5],
            ['month' => '2026-03', 'kind' => 'personal', 'amount' => 20.99],
        ], 2026);
        $this->assertSame(-14.0, $r['opening']);
        $this->assertSame(1699.5, $r['months'][0]['balance']);
        $this->assertSame(1299.5, $r['months'][1]['balance']);
        $this->assertSame(20.99, $r['months'][2]['balance']);
        $this->assertSame(20.99, $r['closing']);
        $this->assertCount(12, $r['months']);
    }

    public function testACreditBalanceMeansTheCompanyOwesHimAndNoWarning(): void
    {
        $this->assertStringContainsString('company owes the shareholder $14.00', ShareholderAccountService::yearEndNote(-14));
        $this->assertStringNotContainsString('15(2)', str_replace('no s.15(2) concern', '', ShareholderAccountService::yearEndNote(-14)));
        $this->assertStringContainsString('s.15(2)', ShareholderAccountService::yearEndNote(1200));
        $this->assertSame([], ShareholderAccountService::briefItems(-14, '2026-12-01'), 'owed TO him → nothing to clear');
        $this->assertSame(-14.0, ShareholderAccountService::FILED_OPENING_DEFAULT);
    }

    // ── DB: import, approve, undo, locked, shareholder ──────────────────────

    public function testImportApproveMovesTheBankLinesAndUndoPutsThemBack(): void
    {
        $db = $this->db();
        $svc = new WavePayrollImportService($db, $this->ledger($db));
        $imp = $svc->import(self::january(), 'jan.pdf', 1);
        $this->assertTrue($imp['ok'], $imp['message']);
        $runId = $imp['run_ids'][0];
        $this->assertSame($imp['run_ids'], $svc->import(self::january(), 'jan.pdf', 1)['run_ids'], 'the same report twice → the same run');

        $rep = $svc->report();
        $this->assertSame([], $rep['account_problems']);
        $prop = $rep['runs'][0]['proposal'];
        $this->assertSame(1213.5, $prop['clearing']['sweep']);
        $this->assertSame(2, $rep['runs'][0]['hours'][0]['user_id'] ?? null, 'Jane matched to her CRM user');
        $this->assertSame(1.0, $rep['runs'][0]['hours'][0]['rows'][0]['diff'], '40 paid vs 39 clocked');

        $ticks = array_column(array_filter($prop['moves'], fn($m) => $m['checked']), 'id');
        $r = $svc->approve($runId, $ticks, 1);
        $this->assertTrue($r['ok'], $r['message']);
        $this->assertSame(8, $r['moved']);

        // Wages counted once: 5100 holds the payroll entry's gross and nothing from the bank.
        $net = $this->net($db);
        $this->assertSame(5000.0, $net[$this->acct($db, '5100')]);
        $this->assertSame(0.0, $net[$this->acct($db, '2310')] ?? 0.0, 'remittance cleared');
        $this->assertSame(0.0, $net[$this->acct($db, '2520')] ?? 0.0, 'net pay cleared');
        $this->assertSame(1213.5, $net[$this->acct($db, '1300')]);
        $this->assertSame(61.6, $net[$this->acct($db, '6800')]);
        $this->assertSame(0.0, round(array_sum($net), 2), 'the journal balances');
        $this->assertSame('2310', $this->codeOf($db, 1));
        $this->assertSame('transfer', $db->query("SELECT type FROM accounting_transactions WHERE id = 1")->fetchColumn());

        $this->assertFalse($svc->approve($runId, $ticks, 1)['ok'], 'booked once');

        $u = $svc->undo($runId, 1);
        $this->assertTrue($u['ok'], $u['message']);
        $net = $this->net($db);
        $this->assertSame(3093.24, $net[$this->acct($db, '5100')], 'back to the bank lines on wages');
        $this->assertSame(3500.0, $net[$this->acct($db, '3300')]);
        $this->assertSame(0.0, $net[$this->acct($db, '1300')] ?? 0.0);
        $this->assertSame('5100', $this->codeOf($db, 1));
        $this->assertSame('preview', $db->query("SELECT status FROM payroll_runs WHERE id = {$runId}")->fetchColumn());
    }

    public function testLockedMonthAndFiledYearAreRefused(): void
    {
        $db = $this->db();
        $svc = new WavePayrollImportService($db, $this->ledger($db));
        $runId = $svc->import(self::january(), 'jan.pdf', 1)['run_ids'][0];
        $db->exec("INSERT INTO accounting_periods (year, month, status) VALUES (2026, 1, 'locked')");
        $r = $svc->approve($runId, [1, 2], 1);
        $this->assertFalse($r['ok']);
        $this->assertStringContainsString('locked', $r['message']);
        $this->assertSame(0, (int)$db->query("SELECT COUNT(*) FROM journal_entries WHERE source_type = 'payroll_run'")->fetchColumn());
        $this->assertSame('5100', $this->codeOf($db, 1), 'nothing moved');
        $this->assertNotNull(WavePayrollImportService::bookableReason(['month' => '2025-12'], false), '2025 is filed');
    }

    public function testRepaymentsPersonalChargesAndTheClearingEntry(): void
    {
        $db = $this->db();
        $ledger = $this->ledger($db);
        $sh = new ShareholderAccountService($db, $ledger);
        // Opening: an old 2025 balance of $86,086, then the FY2026 opening entry (dated Jan 1, source
        // 'fy_opening') takes it to the filed figure — the company owes him $14.
        $db->exec("INSERT INTO journal_entries (id, entry_date, memo, source_type, status) VALUES (899, '2025-06-30', 'old', 'manual', 'posted')");
        $db->exec("INSERT INTO journal_lines (entry_id, account_id, debit, credit) VALUES (899, " . $this->acct($db, '1300') . ", 86086, 0), (899, " . $this->acct($db, '3900') . ", 0, 86086)");
        $db->exec("INSERT INTO journal_entries (id, entry_date, memo, source_type, source_id, status, is_adjusting) VALUES (900, '2026-01-01', 'FY2026 opening', 'fy_opening', 2025, 'posted', 1)");
        $db->exec("INSERT INTO journal_lines (entry_id, account_id, debit, credit) VALUES (900, " . $this->acct($db, '1300') . ", 0, 86100), (900, " . $this->acct($db, '3900') . ", 86100, 0)");
        // The filed figure comes from fy_filed_balances when the table is there (over ops_settings).
        $this->assertSame(-14.0, $sh->filedOpening());
        $db->exec("CREATE TABLE fy_filed_balances (id INTEGER PRIMARY KEY, fiscal_year INTEGER, line TEXT, amount REAL)");
        $db->exec("INSERT INTO fy_filed_balances (fiscal_year, line, amount) VALUES (2025, 'due_from_shareholder', -14.00), (2024, 'due_from_shareholder', 71066)");
        $db->exec("UPDATE ops_settings SET setting_value = '99' WHERE setting_key = 'shareholder_filed_opening'");
        $this->assertSame(-14.0, $sh->filedOpening());

        $p = $sh->proposals();
        $this->assertSame([10], array_column($p['repayments'], 'id'));
        $this->assertSame([11], array_column($p['personal'], 'id'));
        $this->assertFalse($p['personal'][0]['checked'], 'personal is a suggestion');
        $this->assertSame([5, 6, 7], array_column($p['waiting'], 'id'), 'his transfers wait for January\'s payroll');

        $a = $sh->apply([10, 11], 1);
        $this->assertTrue($a['ok'], $a['message']);
        $this->assertSame(2, $a['moved']);
        $L = $sh->ledger();
        $this->assertSame(-14.0, $L['opening']);
        $this->assertNull($L['opening_note'], 'books agree with the filed -$14');
        $this->assertSame(-400.0, $L['months'][0]['repayment']);
        $this->assertSame(20.99, $L['months'][0]['personal']);
        $this->assertSame(-393.01, $L['months'][0]['balance']);
        $this->assertStringContainsString('company owes the shareholder $393.01', $sh->report()['year_end_note']);
        $this->assertSame([], $sh->brief('2026-12-01'));

        $this->assertFalse($sh->addClearing('dividend', '2026-03-31', 1000, 50, '', 1)['ok'], 'no withholdings on a dividend');
        $c = $sh->addClearing('dividend', '2026-03-31', 600, 0, 'per accountant', 1);
        $this->assertTrue($c['ok'], $c['message']);
        $L = $sh->ledger();
        $this->assertSame(-600.0, $L['months'][2]['clearing']);
        $this->assertSame(-993.01, $L['closing']);
        $this->assertSame(600.0, $this->net($db)[$this->acct($db, '3400')]);

        $this->assertTrue($sh->undoClearing($c['id'], 1)['ok']);
        $this->assertSame(-393.01, $sh->ledger()['closing']);
        $this->assertTrue($sh->undoBatch($a['batch_id'], 1)['ok']);
        $this->assertSame(-14.0, $sh->ledger()['closing']);
        $this->assertSame('4900', $this->codeOf($db, 10));

        $b = $sh->addClearing('bonus', '2026-03-31', 1000, 250, '', 1);
        $this->assertTrue($b['ok'], $b['message']);
        $net = $this->net($db);
        $this->assertSame(4343.24, $net[$this->acct($db, '5100')], 'bonus gross $1,250 on top of the $3,093.24 of bank lines');
        $this->assertSame(-250.0, $net[$this->acct($db, '2310')]);
    }

    // ── SQLite fixture ──────────────────────────────────────────────────────

    private function ledger(PDO $db): LedgerService
    {
        return new class($db) extends LedgerService {
            private PDO $pdo;
            public function __construct(PDO $db) { parent::__construct($db); $this->pdo = $db; }
            public function canRepostSource(): bool { return true; }
            public function accountId(string $code): int
            {
                $s = $this->pdo->prepare("SELECT id FROM chart_of_accounts WHERE code = ?");
                $s->execute([$code]);
                return (int)$s->fetchColumn();
            }
        };
    }

    private function acct(PDO $db, string $code): int
    {
        $s = $db->prepare("SELECT id FROM chart_of_accounts WHERE code = ?");
        $s->execute([$code]);
        return (int)$s->fetchColumn();
    }

    private function codeOf(PDO $db, int $txId): string
    {
        return (string)$db->query("SELECT c.code FROM accounting_transactions t JOIN chart_of_accounts c ON c.id = t.account_id WHERE t.id = {$txId}")->fetchColumn();
    }

    private function net(PDO $db): array
    {
        $out = [];
        foreach ($db->query("SELECT account_id, SUM(debit) - SUM(credit) AS n FROM journal_lines GROUP BY account_id")->fetchAll(PDO::FETCH_ASSOC) as $r) {
            $out[(int)$r['account_id']] = round((float)$r['n'], 2);
        }
        return $out;
    }

    private function db(): PDO
    {
        $db = method_exists(PDO::class, 'connect') ? PDO::connect('sqlite::memory:') : new PDO('sqlite::memory:');
        $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        BankLineMoveServiceTest::schema($db);
        foreach ([[20, '5110', 'Employer CPP & EI', 'expense'], [21, '2310', 'Source deductions payable — CRA', 'liability'],
                  [22, '2520', 'Net pay clearing — Wave', 'liability'], [23, '1300', 'Due from Shareholder', 'asset'],
                  [24, '3400', 'Dividends Declared', 'equity'], [25, '6800', 'Bank Charges & Fees', 'expense'],
                  [26, '3300', "Owner's Draw", 'equity'], [27, '3900', 'Opening Balance Equity', 'equity'], [28, '5200', 'Materials', 'expense']] as $a) {
            $db->prepare("INSERT INTO chart_of_accounts (id, code, name, type) VALUES (?, ?, ?, ?)")->execute($a);
        }
        $db->exec("ALTER TABLE accounting_transactions ADD COLUMN notes TEXT");
        $db->exec("CREATE TABLE payroll_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, period_month TEXT, report_from TEXT, report_to TEXT, last_payday TEXT,
                   source_hash TEXT, source_name TEXT, is_estimate INTEGER DEFAULT 0, employee_count INTEGER, gross_wages REAL, ee_fed REAL, ee_prov REAL,
                   ee_ei REAL, ee_cpp REAL, ee_cpp2 REAL, er_ei REAL, er_cpp REAL, er_cpp2 REAL, withholdings REAL, employer_cost REAL, net_pay REAL,
                   remittance REAL, sweep_amount REAL, warnings TEXT, status TEXT DEFAULT 'preview', journal_entry_id INTEGER, last_reversal_entry_id INTEGER,
                   created_by INTEGER, created_at TEXT, booked_by INTEGER, booked_at TEXT, undone_by INTEGER, undone_at TEXT)");
        $db->exec("CREATE TABLE payroll_run_employees (id INTEGER PRIMARY KEY AUTOINCREMENT, run_id INTEGER, employee_name TEXT, first_name TEXT, last_name TEXT,
                   user_id INTEGER, gross_wages REAL, ee_fed REAL, ee_prov REAL, ee_ei REAL, ee_cpp REAL, ee_cpp2 REAL, er_ei REAL, er_cpp REAL, er_cpp2 REAL,
                   net_pay REAL, hours REAL)");
        $db->exec("CREATE TABLE payroll_run_paydays (id INTEGER PRIMARY KEY AUTOINCREMENT, run_employee_id INTEGER, payday TEXT, period_start TEXT, period_end TEXT,
                   regular_hours REAL, overtime_hours REAL, double_time_hours REAL, vacation_hours REAL, sick_hours REAL)");
        $db->exec("CREATE TABLE payroll_bank_moves (id INTEGER PRIMARY KEY AUTOINCREMENT, run_id INTEGER, batch_id TEXT, transaction_id INTEGER, role TEXT,
                   employee_name TEXT, amount REAL, old_account_id INTEGER, old_type TEXT, new_account_id INTEGER, moved_by INTEGER, moved_at TEXT,
                   undone_by INTEGER, undone_at TEXT)");
        $db->exec("CREATE TABLE shareholder_clearings (id INTEGER PRIMARY KEY AUTOINCREMENT, clearing_type TEXT, entry_date TEXT, amount REAL, withholdings REAL,
                   note TEXT, journal_entry_id INTEGER, reversal_entry_id INTEGER, created_by INTEGER, created_at TEXT, undone_by INTEGER, undone_at TEXT)");
        $db->exec("CREATE TABLE ops_settings (id INTEGER PRIMARY KEY AUTOINCREMENT, setting_key TEXT UNIQUE, setting_value TEXT, description TEXT, updated_by INTEGER)");
        $db->exec("INSERT INTO ops_settings (setting_key, setting_value) VALUES ('payroll_shareholder_name', 'Pat Owner'), ('shareholder_filed_opening', '-14.00')");
        $db->exec("CREATE TABLE users (id INTEGER PRIMARY KEY, full_name TEXT)");
        $db->exec("INSERT INTO users (id, full_name) VALUES (1, 'Pat Owner'), (2, 'Jane Doe')");
        $db->exec("CREATE TABLE time_clock_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, clock_in TEXT, clock_out TEXT, total_minutes INTEGER, status TEXT)");
        // Jane clocked 39 h in the first pay period (Wave paid 40).
        foreach (['2025-12-29', '2025-12-30', '2025-12-31', '2026-01-02', '2026-01-05'] as $i => $d) {
            $db->prepare("INSERT INTO time_clock_entries (user_id, clock_in, clock_out, total_minutes, status) VALUES (2, ?, ?, ?, 'completed')")
               ->execute([$d . ' 08:00:00', $d . ' 16:00:00', $i === 4 ? 420 : 480]);
        }

        // The bank lines (as imported, with their journal entries — wages on 5100, his transfers on 3300).
        foreach (self::bank() as $l) {
            $type = $l['direction'] === 'in' ? 'income' : (in_array($l['account_code'], ['3300'], true) ? 'transfer' : 'expense');
            $db->prepare("INSERT INTO accounting_transactions (id, transaction_date, type, amount, description, account_id, reference_type, bank_account_id)
                          VALUES (?, ?, ?, ?, ?, ?, 'bank_import', 1)")->execute([$l['id'], $l['date'], $type, $l['amount'], $l['description'], $this->acct($db, $l['account_code'])]);
        }
        $db->prepare("INSERT INTO accounting_transactions (id, transaction_date, type, amount, description, account_id, reference_type, bank_account_id)
                      VALUES (11, '2026-01-05', 'expense', 20.99, 'NETFLIX.COM 866-579-7172', ?, 'bank_import', 1)")->execute([$this->acct($db, '6900')]);
        $sync = new LedgerSyncService($db, $this->ledger($db));
        $ledger = $this->ledger($db);
        foreach ($db->query("SELECT id FROM accounting_transactions")->fetchAll(PDO::FETCH_COLUMN) as $id) {
            $args = $sync->bankEntryArgsFor((int)$id);
            if ($args) $ledger->postManual($args);
        }
        return $db;
    }
}
