<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';

$pageTitle       = 'Privacy Policy | Mowology Landscaping';
$pageDescription = 'How Mowology Landscaping collects, uses, and protects your personal information under PIPEDA.';
$activeNav       = '';
?>
<?php require __DIR__ . '/includes/head.php'; ?>
<?php require __DIR__ . '/includes/header.php'; ?>

<div class="privacy-hero">
    <div class="container">
        <h1>Privacy Policy</h1>
        <p class="privacy-updated">Effective date: March 22, 2026 &bull; Mowology Landscaping (Vancouver, BC)</p>
    </div>
</div>

<div class="container">
<div class="privacy-layout">

    <!-- Table of contents -->
    <nav class="privacy-toc" aria-label="Privacy policy sections">
        <div class="privacy-toc-title">Contents</div>
        <a href="#who-we-are">1. Who We Are</a>
        <a href="#what-we-collect">2. What We Collect</a>
        <a href="#why-we-collect">3. Why We Collect It</a>
        <a href="#sms-consent">4. SMS &amp; Email Consent</a>
        <a href="#photos">5. Service Photos</a>
        <a href="#location">6. Location Tracking</a>
        <a href="#payments">7. Payment Information</a>
        <a href="#retention">8. Data Retention</a>
        <a href="#your-rights">9. Your Rights (PIPEDA)</a>
        <a href="#third-parties">10. Third Parties</a>
        <a href="#contact">11. Contact Us</a>
    </nav>

    <!-- Policy body -->
    <main>

        <section class="privacy-section" id="who-we-are">
            <h2>1. Who We Are</h2>
            <p>
                Mowology Landscaping is a landscaping and grounds maintenance company operating in Metro Vancouver,
                British Columbia, Canada. We provide services to residential and commercial property owners.
            </p>
            <p>
                This Privacy Policy describes how we collect, use, disclose, and protect personal information
                in accordance with the <em>Personal Information Protection and Electronic Documents Act</em>
                (PIPEDA), federal privacy legislation applicable to our operations.
            </p>
        </section>

        <section class="privacy-section" id="what-we-collect">
            <h2>2. What Personal Information We Collect</h2>
            <table class="privacy-table">
                <thead>
                    <tr><th>Category</th><th>Examples</th><th>Source</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Identity</strong></td>
                        <td>First name, last name</td>
                        <td>You provide it when requesting a quote or signing a contract</td>
                    </tr>
                    <tr>
                        <td><strong>Contact</strong></td>
                        <td>Email address, phone number, mobile number</td>
                        <td>Quote request form, direct communication</td>
                    </tr>
                    <tr>
                        <td><strong>Property</strong></td>
                        <td>Service address, city, province, postal code</td>
                        <td>Quote request form</td>
                    </tr>
                    <tr>
                        <td><strong>Service history</strong></td>
                        <td>Past quotes, invoices, service plans, visit dates</td>
                        <td>Generated by us as part of service delivery</td>
                    </tr>
                    <tr>
                        <td><strong>Payment reference</strong></td>
                        <td>Last 4 digits of card, card brand (Visa, Mastercard), Stripe customer ID</td>
                        <td>Stripe payment processing (see Section 7)</td>
                    </tr>
                    <tr>
                        <td><strong>Communications</strong></td>
                        <td>SMS and email consent status, consent timestamps, opt-out records</td>
                        <td>You provide consent during quote or contract workflow</td>
                    </tr>
                    <tr>
                        <td><strong>Device &amp; technical</strong></td>
                        <td>IP address at time of form submission or contract signing</td>
                        <td>Automatically captured for fraud prevention and legal proof of consent</td>
                    </tr>
                </tbody>
            </table>
            <p>We do <strong>not</strong> collect: government-issued ID numbers, SIN, health information,
               or any information from children under 13.</p>
        </section>

        <section class="privacy-section" id="why-we-collect">
            <h2>3. Why We Collect It</h2>
            <ul>
                <li><strong>Service delivery</strong> — scheduling visits, dispatching crew, tracking service at your property</li>
                <li><strong>Billing and invoicing</strong> — generating invoices, processing payments, maintaining financial records</li>
                <li><strong>Communication</strong> — sending appointment reminders, service updates, and quote follow-ups (with your consent)</li>
                <li><strong>Legal compliance</strong> — Canadian tax law (ITA s.230) requires us to retain financial records for 7 years</li>
                <li><strong>Safety and fraud prevention</strong> — verifying identity for contract signing, detecting abuse</li>
            </ul>
            <p>We collect the minimum information necessary for these purposes.</p>
        </section>

        <section class="privacy-section" id="sms-consent">
            <h2>4. SMS &amp; Email Consent</h2>
            <p>
                We send SMS messages only to clients who have explicitly opted in. Consent is recorded with
                a timestamp and the source of collection (e.g., quote request form). You can withdraw consent
                at any time by:
            </p>
            <ul>
                <li>Replying <strong>STOP</strong> to any SMS from us</li>
                <li>Emailing <a href="mailto:office@mowology.ca">office@mowology.ca</a></li>
                <li>Calling us at <a href="tel:7788469273">(778) 846-9273</a></li>
            </ul>
            <p>
                SMS messages are sent via Canadian carrier email-to-SMS gateways. Message frequency varies.
                Standard messaging rates may apply. We do not send marketing SMS — only transactional messages
                (appointment reminders, service notifications).
            </p>
            <p>
                Marketing emails are sent only with your explicit consent. You can unsubscribe from any
                marketing email using the unsubscribe link included in each message.
            </p>
        </section>

        <section class="privacy-section" id="photos">
            <h2>5. Service Photos</h2>
            <p>
                Our crew photographs service areas before and after each visit as proof-of-work documentation.
                These photos may include images of your property. Photos are stored securely and accessible
                only to Mowology staff.
            </p>
            <p>
                Photos are not shared with third parties and are not used for marketing without explicit
                additional consent. You may request deletion of your service photos by submitting a
                <a href="/privacy-request">Privacy Request</a>.
            </p>
        </section>

        <section class="privacy-section" id="location">
            <h2>6. Location Tracking (Crew Only)</h2>
            <p>
                GPS location tracking applies <strong>only to our crew members</strong>, not to clients.
                Location data is used to verify on-site arrival, automate clock-in/clock-out, and improve
                scheduling accuracy.
            </p>
            <p>Location tracking requires per-employee opt-in and can be disabled by the employee.</p>
            <table class="privacy-table">
                <thead>
                    <tr><th>Data Type</th><th>Retention Period</th></tr>
                </thead>
                <tbody>
                    <tr><td>Real-time location pings (crew)</td><td>90 days</td></tr>
                    <tr><td>GPS breadcrumb trail per visit</td><td>180 days</td></tr>
                    <tr><td>Visit arrival/departure GPS coordinates</td><td>Duration of employment + 2 years</td></tr>
                </tbody>
            </table>
            <p>Location data is automatically purged on schedule. Employees may request earlier deletion.</p>
        </section>

        <section class="privacy-section" id="payments">
            <h2>7. Payment Information &amp; PCI DSS</h2>
            <div class="privacy-pci-note">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                </svg>
                <div>
                    <strong>Mowology never sees, stores, or transmits your full credit card number.</strong>
                    Payments are processed by <strong>Stripe</strong>, a PCI DSS Level 1 certified payment processor.
                    We store only the last 4 digits of your card and your Stripe customer ID for reference.
                    Mowology operates under Stripe's SAQ-A PCI DSS compliance scope.
                </div>
            </div>
            <p>
                Stripe's privacy policy is available at
                <a href="https://stripe.com/en-ca/privacy" rel="noopener noreferrer" target="_blank">stripe.com/en-ca/privacy</a>.
            </p>
        </section>

        <section class="privacy-section" id="retention">
            <h2>8. Data Retention</h2>
            <table class="privacy-table">
                <thead>
                    <tr><th>Data Category</th><th>Retention Period</th><th>Reason</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Client contact information</td>
                        <td>Duration of relationship + 3 years</td>
                        <td>Service continuity, dispute resolution</td>
                    </tr>
                    <tr>
                        <td>Financial records (invoices, quotes, payments)</td>
                        <td>7 years from transaction date</td>
                        <td>CRA / ITA s.230 legal requirement</td>
                    </tr>
                    <tr>
                        <td>Consent records (SMS/email opt-in)</td>
                        <td>7 years from consent date</td>
                        <td>CASL compliance and legal proof</td>
                    </tr>
                    <tr>
                        <td>Service photos</td>
                        <td>3 years after last service</td>
                        <td>Dispute resolution, proof-of-work</td>
                    </tr>
                    <tr>
                        <td>Crew GPS pings</td>
                        <td>90 days (auto-purged)</td>
                        <td>Data minimisation</td>
                    </tr>
                    <tr>
                        <td>Visit GPS breadcrumbs</td>
                        <td>180 days (auto-purged)</td>
                        <td>Data minimisation</td>
                    </tr>
                    <tr>
                        <td>System audit logs</td>
                        <td>2 years</td>
                        <td>Security and compliance</td>
                    </tr>
                </tbody>
            </table>
            <p>When data is no longer required, it is securely deleted or anonymised.</p>
        </section>

        <section class="privacy-section" id="your-rights">
            <h2>9. Your Rights Under PIPEDA</h2>
            <p>You have the right to:</p>
            <ul>
                <li><strong>Access</strong> — request a copy of the personal information we hold about you</li>
                <li><strong>Correction</strong> — request correction of inaccurate information</li>
                <li><strong>Erasure</strong> — request deletion of your personal information (subject to legal hold requirements for financial records)</li>
                <li><strong>Withdraw consent</strong> — for marketing or SMS communications at any time</li>
                <li><strong>Complaint</strong> — lodge a complaint with the
                    <a href="https://www.priv.gc.ca/en/report-a-concern/" rel="noopener noreferrer" target="_blank">
                        Office of the Privacy Commissioner of Canada
                    </a>
                </li>
            </ul>
            <p>
                We will respond to access and correction requests within <strong>30 days</strong> as required by PIPEDA.
                Erasure requests will be processed within 30 days; certain data may be retained under legal-hold exceptions.
            </p>
            <p>
                <a href="/privacy-request" class="btn-primary" style="display:inline-block;margin-top:8px;
                   padding:10px 24px;background:var(--mowology-green,#2D8659);color:#fff;
                   border-radius:6px;text-decoration:none;font-weight:600;">
                    Submit a Privacy Request
                </a>
            </p>
        </section>

        <section class="privacy-section" id="third-parties">
            <h2>10. Third-Party Services</h2>
            <table class="privacy-table">
                <thead>
                    <tr><th>Service</th><th>Purpose</th><th>Data Shared</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Stripe (payment processing)</td>
                        <td>Credit card payment processing</td>
                        <td>Name, email, billing address, card details</td>
                    </tr>
                    <tr>
                        <td>Google Maps (address lookup)</td>
                        <td>Address autocomplete and geocoding</td>
                        <td>Property address</td>
                    </tr>
                    <tr>
                        <td>Open-Meteo (weather data)</td>
                        <td>Weather-based scheduling</td>
                        <td>Property coordinates (approximate)</td>
                    </tr>
                    <tr>
                        <td>Canadian Web Hosting (hosting)</td>
                        <td>Web hosting in Canada</td>
                        <td>All data stored on Canadian servers</td>
                    </tr>
                </tbody>
            </table>
            <p>We do not sell, rent, or trade personal information to third parties for marketing purposes.</p>
            <p>All data is stored in Canada.</p>
        </section>

        <section class="privacy-section" id="contact">
            <h2>11. Contact Us</h2>
            <p>
                For privacy questions, concerns, or to exercise your rights under PIPEDA, contact our
                Privacy Officer:
            </p>
            <div class="privacy-contact-card">
                <strong>Mowology Landscaping</strong><br>
                Attn: Privacy Officer<br>
                Vancouver, British Columbia, Canada<br>
                <a href="mailto:office@mowology.ca">office@mowology.ca</a><br>
                <a href="tel:7788469273">(778) 846-9273</a>
            </div>
            <p style="margin-top:16px;">
                You may also submit a request online at <a href="/privacy-request">/privacy-request</a>.
                We will respond within 30 days.
            </p>
        </section>

    </main>
</div>
</div>

<?php require __DIR__ . '/includes/footer.php'; ?>
