/* Marketing Studio — workflow content. Plain data; edit freely. */
window.STUDIO = {
  steps: [
    { key: 'choose', title: 'Choose the piece', lede: 'One piece, one channel, one action. Everything downstream is decided by what this is.' },
    { key: 'brief',  title: 'Write the brief',  lede: 'Rule of One: one idea, one emotion, one story, one benefit, one response. If a line here has an "and" in it, split the piece.' },
    { key: 'voice',  title: 'Voice and rules',  lede: 'The voice card was extracted from your own writing. The never-list is the part that keeps every channel sounding like one company.' },
    { key: 'claude', title: 'Hand to Claude',   lede: 'The Studio writes the brief to the outbox. Claude reads it with /studio, runs the right skill, and writes the draft back here.' },
    { key: 'review', title: 'Review the draft', lede: 'Read it aloud once. Then tick the rubric; anything unticked goes back with a note.' },
    { key: 'ship',   title: 'Ship it',          lede: 'Where it goes, what to check as it goes, and what to watch afterwards.' },
  ],

  types: [
    { id: 'service_page', tactics: ['true_competitor', 'find_the_fear', 'category_cliches', 'only_better', 'value_mining', 'movie_time'],  label: 'Service landing page', skills: ['copywriting', 'page-cro', 'ai-seo'],
      ship: 'File-based page (includes/service-data) or a CMS page under services/', length: '700–1,000 words, FAQ of 5, one CTA',
      blurb: 'A page that owns one search intent. Opens with a direct answer for a solution-aware reader.',
      shipList: ['Deployed to production and renders to </html>', 'Title ≤ 60 chars, description ≤ 155', 'Appears in footer and related-services (automatic for file-based)', 'Request indexing in Search Console (mowology.ca Domain property)', 'Watch impressions for the target query after 14 days'] },
    { id: 'blog_guide', tactics: ['whats_it_about', 'shock_old', 'movie_time', 'story_hooks', 'three'],    label: 'Blog guide', skills: ['copywriting', 'ai-seo'],
      ship: 'Content Engine → Prepared drafts or Generate → Publish', length: '800–1,300 words; 40–60 word quick answer first; FAQ block',
      blurb: 'Answers a question a council or homeowner actually asks. The AI-citation layer of the site.',
      shipList: ['Loaded into Content Engine and published to /blog/<slug>', 'Hero image chosen from the media library', 'BlogPosting + FAQPage schema present (Rich Results Test)', 'Cascade run: social + email drafts reviewed', 'Request indexing in Search Console'],
      links: [{ label: 'Open Content Engine', url: 'https://mowology.ca/crm/marketing/content-engine.php' }] },
    { id: 'quote_followup', tactics: ['find_the_fear', 'simple_sales', 'rolls_royce', 'leave_it_out'], label: 'Quote follow-up email', skills: ['email-sequence', 'copywriting'],
      ship: 'CRM email template or a one-off from Tim', length: 'Under 150 words, one ask, one attachment named',
      blurb: 'Day-3 email after a site walk. Leads with the one objection you heard, answers it, attaches the artefact that helps them decide.',
      shipList: ['Signed as Tim, plain text, no exclamation marks', 'Objection named in the first line', 'Scope sheet or comparison attached', 'Send time set (weekday morning)', 'Reply logged in the CRM'] },
    { id: 'email_sequence', tactics: ['man_in_hole', 'simple_sales', 'three', 'leave_it_out'], label: 'Email sequence', skills: ['email-sequence'],
      ship: 'CRM campaigns (Marketing → Campaigns)', length: '3–5 emails, each under 200 words',
      blurb: 'Nurture, seasonal (fall cleanup, winter plan), or win-back. Cadence and structure first, then the words.',
      shipList: ['Each email has one ask', 'Unsubscribe and sender identity from business_settings', 'Consent respected (no SMS to opted-out contacts)', 'First send to a test contact', 'Open/reply rates checked after 7 days'],
      links: [{ label: 'Open Campaigns', url: 'https://mowology.ca/crm/marketing/campaigns.php' }] },
    { id: 'social_post', tactics: ['rolls_royce', 'show_dont_tell', 'pub_language', 'story_hooks'],   label: 'Social post or calendar', skills: ['social-content'],
      ship: 'Social Library / Calendar (Marketing → Social)', length: 'Caption under 60 words; 30-day calendar if a calendar',
      blurb: 'Before/after plus one specific sentence in the customer’s words. No hashtag walls.',
      shipList: ['Photo consent confirmed for any client property', 'Caption uses customer language, no emoji walls', 'Scheduled in the social calendar', 'Meta connection healthy (check Social Accounts)'],
      links: [{ label: 'Open Social Calendar', url: 'https://mowology.ca/crm/marketing/social-calendar.php' }] },
    { id: 'gbp_post', tactics: ['movie_time', 'pub_language', 'leave_it_out'],      label: 'Google Business Profile post', skills: ['copywriting'],
      ship: 'Google Business Profile → Posts', length: 'Under 100 words, one photo, one button',
      blurb: 'Weekly post to the profile that feeds the map pack. Seasonal, specific, local.',
      shipList: ['Posted with a real job photo', 'Button points to the matching service page', 'Ask-for-reviews link used where appropriate'],
      links: [{ label: 'Open Business Profile', url: 'https://www.google.com/maps?cid=15220268177293590228' }] },
    { id: 'ad', tactics: ['category_cliches', 'story_hooks', 'real_product', 'value_mining'],            label: 'Ad (Google or Meta)', skills: ['ad-creative', 'paid-ads', 'copywriting'],
      ship: 'Google Ads / Meta Ads Manager', length: 'Per platform spec: 5 headlines, 3 descriptions, or primary text + headline',
      blurb: 'Hooks and angles for one service and one city. Caples formulas are the testing backbone.',
      shipList: ['Landing page matches the ad promise', 'Conversion tracking on the quote form', 'Budget and geo set (Vancouver, Burnaby, Richmond)', 'Two variants live for a fair test'] },
    { id: 'proposal', tactics: ['pitch_perfect', 'hero_guide', 'only_better', 'value_mining', 'contrarian'],      label: 'Proposal cover letter', skills: ['copywriting', 'sales-enablement'],
      ship: 'PDF proposal from the CRM, or a signed letter', length: 'One page; three expected objections answered; price reframed',
      blurb: 'Written to survive being forwarded around a council. Their words for their problem first.',
      shipList: ['Opens with the site-walk observation in their words', 'Three objections answered with proof beside each', 'Price shown per unit per month', 'Scope sheet and calendar attached', 'Start date and next step named'] },
    { id: 'tagline', tactics: ['real_product', 'pub_language', 'three', 'whats_it_about'],       label: 'Truck, shirt or signage line', skills: ['copywriting'],
      ship: 'Print vendor / vehicle wrap', length: 'One line; seen for three seconds from thirty feet',
      blurb: 'Who it’s for and one specific promise. Keep the phone number.',
      shipList: ['Legible at distance in a proof', 'Phone number and mowology.ca present', 'Compliance check on any claim', 'Consistent with the site’s wording'] },
    { id: 'review_reply', tactics: ['hero_guide', 'show_dont_tell', 'leave_it_out'],  label: 'Reply to a review', skills: ['copywriting'],
      ship: 'Google / HomeStars / Yelp', length: '2–4 sentences, first person, signed Tim',
      blurb: 'Every reply is read by the next council member deciding whether to call. Specific, warm, no defensiveness.',
      shipList: ['Names something specific from the review', 'No arguing with a critical review; offer a call', 'Signed Tim'] },
  ],

  audiences: [
    { id: 'strata',  label: 'Strata council', note: 'Volunteers, risk-averse, decide by committee, compare three quotes.' },
    { id: 'pm',      label: 'Property manager', note: 'Paid to reduce their own workload and exposure. Wants one number, one contact.' },
    { id: 'home',    label: 'Homeowner', note: 'Personal money, personal garden. Values being listened to.' },
    { id: 'commercial', label: 'Commercial property', note: 'Offices, retail, business parks. First impressions at the curb.' },
  ],

  awareness: [
    { id: 'unaware',   label: 'Unaware',        lead: 'Proclamation or Story', note: 'Doesn’t know there’s a problem. Open with a true, surprising fact or a story; sell nothing yet.' },
    { id: 'problem',   label: 'Problem-aware',  lead: 'Problem-Solution', note: 'Has the worry, not the solution. Name the worry in their words, prove you’ve seen it, then hope.' },
    { id: 'solution',  label: 'Solution-aware', lead: 'Secret or Promise', note: 'Knows the result they want, not that you provide it. Show you understand the outcome, then that you deliver it.' },
    { id: 'product',   label: 'Product-aware',  lead: 'Promise, then proof', note: 'Knows you, unsure it’s right. Less explaining, more proving.' },
    { id: 'most',      label: 'Most aware',     lead: 'Offer', note: 'Knows you and only needs the deal. Lead with the offer.' },
  ],

  proofs: [
    'Photo report after every visit', '$5M liability insurance', 'WorkSafeBC coverage', 'Founded 2012',
    '250+ properties maintained', '56 Google reviews at 4.5', 'HomeStars 4.6 (17 reviews)', 'Response within 24 hours, usually same day',
    'Storm call-outs within 24 hours', 'Dedicated crew per route', 'Named account contact',
  ],

  compliance: [
    'A specific number or percentage', 'A testimonial or named customer', 'A guarantee or "guaranteed" wording',
    'A price or "from $" claim', 'A comparison naming a competitor', 'A claim about equipment (electric, no fumes) not yet confirmed',
  ],

  reviewRubric: [
    'Lead type is the right one for the awareness stage, and there is only one lead',
    'Rule of One: one idea, one emotion, one benefit, one response',
    'Every objection this buyer raises is answered, in their words, with proof beside it',
    'Headline scores on the 4 U’s (urgent, unique, ultra-specific, useful)',
    'No invented numbers; every proof is on the true-proof list',
    'Voice card holds: no exclamation marks, no "elevate/solution/exceptional", concrete words',
    'FAQ answers are self-contained and 40–60 words (if there is a FAQ)',
    'One clear CTA, named for what they get',
    'Read aloud once without stumbling',
  ],

  keywordHints: [
    'lawn care vancouver', 'yard maintenance vancouver', 'lawn maintenance vancouver', 'strata landscaping vancouver',
    'commercial landscape maintenance vancouver', 'hedge trimming vancouver', 'vancouver snow removal company',
    'kitsilano landscaping', 'professional landscaping richmond', 'power raking lawn', 'fall cleanup vancouver',
  ],
  keywordHintNote: 'Queries Google already shows the site for (Search Console, 23 Sep 2026). Pick one; the CRM’s SEO Recommendations page has the full ranked list.',

  /* Tactics — concept cards from Pip Decks' Brand Tactics and Storyteller Tactics, in our own words.
     `mow` is Mowology's standing answer (from .agents/product-marketing-context.md); the owner adds the answer for THIS piece. */
  tactics: {
    decks: { brand: 'Brand Tactics', story: 'Storyteller Tactics' },
    strategyCards: ['true_competitor', 'find_the_fear', 'only_better', 'value_mining', 'real_product', 'contrarian', 'pub_language'],
    cards: [
      { id: 'true_competitor', deck: 'brand', name: 'The True Competitor', ask: 'What is this reader actually choosing instead of us? It is rarely another landscaper.',
        mow: 'The contractor they already have. The cheapest of three quotes. An in-house caretaker. Doing nothing until spring.' },
      { id: 'find_the_fear', deck: 'brand', name: 'Find The Fear', ask: 'Name the fear underneath the request. Copy that answers the fear outsells copy that describes the service.',
        mow: 'Council: a slip claim or a resident complaint with no record to show. Manager: being the one who gets chased. Homeowner: paying for visits nobody can see.' },
      { id: 'category_cliches', deck: 'brand', name: 'Category Clichés', ask: 'What every landscaper says. Don’t say it, or say the opposite on purpose.',
        mow: '“Professional, reliable, affordable.” “Your satisfaction is our priority.” “Transform your outdoor space.” The striped-lawn stock photo.' },
      { id: 'only_better', deck: 'brand', name: 'Only Is Better Than Best', ask: 'What do we do that they simply don’t? Facts, not adjectives. “Only” beats “best”.',
        mow: 'A photo report after every visit. A dedicated crew per route. A named account contact. A CRM built around proof of work.' },
      { id: 'value_mining', deck: 'brand', name: 'Value Mining', ask: 'Turn the difference into what it lets the reader do, or stop doing.',
        mow: 'Photo report → no driving over to check. A record if a claim arrives. The manager stops chasing anyone.' },
      { id: 'real_product', deck: 'brand', name: 'The Real Product', ask: 'What are they really buying? It is rarely the cut.',
        mow: 'Not landscaping. Proof the work was done, and one fewer thing to chase.' },
      { id: 'contrarian', deck: 'brand', name: 'Contrarian Value', ask: 'What does the category believe that we openly disagree with?',
        mow: 'That the lowest of three quotes is the safe choice. That “trust us” counts as a report.' },
      { id: 'pub_language', deck: 'brand', name: 'Pub Language', ask: 'Say it the way a customer would explain us to a friend over a pint.',
        mow: '“They show up, they do what I ask, and they send me a photo.”' },
      { id: 'rolls_royce', deck: 'story', name: 'Rolls Royce Moment', ask: 'One vivid, specific detail that carries the whole claim. Ten general claims lose to it.',
        mow: 'Pattern: the treasurer who stopped driving over on Thursdays once the photos started arriving. Use a real one from the site walk.' },
      { id: 'simple_sales', deck: 'story', name: 'Simple Sales Story', ask: '“Someone like you uses this.” Name the kind of customer and what changed for them.' },
      { id: 'pitch_perfect', deck: 'story', name: 'Pitch Perfect', ask: 'Problem, then Opportunity, then Practical steps, then Promise. The order for any pitch or cover letter.' },
      { id: 'man_in_hole', deck: 'story', name: 'Man In A Hole', ask: 'Comfort, trigger, the hole, the climb out, better than before. The shape of every customer story.' },
      { id: 'hero_guide', deck: 'story', name: 'Hero & Guide', ask: 'The customer is the hero. We are the guide: empathy first, then authority. Never the hero of our own copy.' },
      { id: 'movie_time', deck: 'story', name: 'Movie Time', ask: 'Replace every abstraction with a scene you could film.',
        mow: '“Reliable” → the same two people every Tuesday at eight. “Communicative” → a photo in your inbox before the truck has left the street.' },
      { id: 'show_dont_tell', deck: 'story', name: 'Show, Don’t Tell', ask: 'A scene beats a summary. Let the reader conclude “reliable” themselves.' },
      { id: 'story_hooks', deck: 'story', name: 'Story Hooks', ask: 'Simple, Unexpected, Concrete, Credible, Emotional, a Story. Run the opening line through all six.' },
      { id: 'three', deck: 'story', name: 'Three Is The Magic Number', ask: 'Three items, not four, not two. The third one lands.' },
      { id: 'leave_it_out', deck: 'story', name: 'Leave It Out', ask: 'Cut anything that doesn’t serve the one action. Especially the second benefit.' },
      { id: 'shock_old', deck: 'story', name: 'Shock Of The Old', ask: 'Make the familiar strange again. What does everyone assume about lawn care that we can make them look at fresh?' },
      { id: 'five_ts', deck: 'story', name: 'Five Ts', ask: 'Territory, Trouble, Turning point, Transformation, Takeaway. The frame for a testimonial or case study.' },
      { id: 'whats_it_about', deck: 'story', name: 'What’s It About?', ask: 'The whole piece in one sentence. If you can’t write it, the brief isn’t done.' },
    ],
  },

  lengths: ['Short (under 150 words)', 'Standard (300–600 words)', 'Long (800–1,300 words)', 'One line'],
};
